### ISSUE TITLE
Vertical scroll on mousemove event

### ISSUE THREAD

**Issue by Schascha** [schorfES/caroucssel#1]
An option to enable scroll by mouse dragging will be helpful for users without a vertical scroll wheel.

**Comment by schorfES** [comment]
Hi @Schascha,

I am happy to announce that this feature is now available in [version 1.0.0](https://github.com/schorfES/caroucssel/releases/tag/v1.0.0). Please have a look into the [README](https://github.com/schorfES/caroucssel#mouse) to read more about the usage.

Happy to get some feedback.
