### ISSUE TITLE
Disable only the first pagination button

### ISSUE THREAD

**Issue by Schascha** [schorfES/caroucssel#2]
Disable only the first pagination button if multiple slides are shown at once.

**Comment by schorfES** [comment]
You mean a grouping of slides by viewport?

**Comment by schorfES** [comment]
Hi @Schascha, the feature for _pages_ is now published to npm in version [0.6.0](https://github.com/schorfES/caroucssel/releases/tag/v0.6.0). Does the new behaviour solves your issues?

**Comment by schorfES** [comment]
Its related to #6

**Comment by schorfES** [comment]
Solved in #6
