### ISSUE TITLE
Ignore elements inside .scroller

### ISSUE THREAD

**Issue by schulke-214** [schorfES/caroucssel#7]
I came across a situation where I needed an overlay within the `.scroller` container. This irritated the pagination, as it was counted as "content".

It would be useful to have the possiblity to define a selector that ignores items inside the `.scroller` container.

**Comment by schorfES** [comment]
Hi @schulke-214, all childs are counted as "content" because the scrolling is the native css scrolling and applies to the scroll container. If you need to add some additional layers that should be hidden you should better place them inside each slide, or outside of a common container aside to the carousel.

**Comment by schulke-214** [comment]
I tried both ideas and none of them really fullfilled our needs. We wanted to have a Layer with particles above the cards on https://www.moccu.com/about (at the bottom of the page)

They should’ve been scrollable aswell, in the same slider instance - they just shouldn’t show up in the slider controls as seperate element.

**Comment by schorfES** [comment]
Hi @schulke-214, i've added a feature that ignores "invisible" elements like `<link>` or `<script>` by default. Also elements using a `hidden` attribute (`<div hidden>item</div>`) will be ignored. To manually filter items a new option `filterItem` is introduced in (#22). This is a function that allows to filter specific elements (for example by classname). 

I've created a prerelease that is combining all upcoming new features including this one. This is currently testable with the npm tag caroucssel@next. (Using this will bring some breaking changes to the current behaviour).

**Comment by schorfES** [comment]
This feature is published to npm in version [0.6.0](https://github.com/schorfES/caroucssel/releases/tag/v0.6.0). The documentation how to use filters is available here: https://github.com/schorfES/caroucssel#filters
