### ISSUE TITLE
Glitchy Scrolling Behavior

### ISSUE THREAD

**Issue by schulke-214** [schorfES/caroucssel#92]
I updated your lib to the latest version and now we have a glitchy behavior in our team slider:
https://www.moccu.com/about/

I'll provide you  an example in a seperate repository, since i'll fix the issue on our live website very soon.

**Comment by schulke-214** [comment]
Nvm, it's not the latest version.

**Comment by schulke-214** [comment]
Okay, it seems to be happening **in** version `^0.4.2` and not in the current one. Sorry!

**Comment by schorfES** [comment]
@schulke-214 this seem to depend on the animation lib you use. Run the following code in you console to remove the animation instructions:

```
document.querySelectorAll('[data-animatable]').forEach((el) => {
  delete(el.dataset.animatable);
  delete(el.dataset.animationType);
});
```

It also seems that the CSS is not fully loaded when the carousel is initialized. This causes the carousel to miss-calculate the pages and sizes - resulting in an error in the console.
